spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true
    cache:
      disabled: true
  show-spring-security: true
  packages-to-scan: ru.don_polesie.back_end.controller


logging:
  level:
    org.springframework: INFO
    com.example.demo: DEBUG
    org.hibernate: WARN
  file:
    name: logs/application.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


server:
  port: ${SERVER_PORT:8080}

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:your-very-secure-secret-key-with-at-least-32-characters}
    access: ${SECURITY_JWT_ACCESS:3600000}
    refresh: ${SECURITY_JWT_REFRESH:2592000000}
    issuer: ${SECURITY_JWT_ISSUER:delivery-admin}
  YooKassa:
    shopId: ${YOOKASSA_SHOP_ID:1135993}
    secretKey: ${YOOKASSA_SECRET_KEY:test_bZX-_VfdaX0Rr3EPRdubMCzq5hJVdNpZ6e4ZvaVaAgM}

import:
  directory: ${IMPORT_DIRECTORY:/data/import}
